name: Go CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build_and_test:
    runs-on: windows-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: build application
        run: make build

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Run tests
        run: go test -race -vet=off ./...
